### PR TITLE
Update for Ani >= 2.1.45

### PR DESCRIPTION
**Pull request by RisingOrange**
I moved the code in my anki add-on template, but maybe you can use some code from this.

### CODE REVIEW

**Comment by phu54321** [comment]
This seems great, except that I'm using [trgkanki-template-cli](https://github.com/trgkanki/trgkanki-template-cli) instead of _aab_. This basic2cloze is a kind of legacy addon, so it doesn't use either right now. Would it be possible to remove aab dependency?

FYI I could do that myself (I'll just close this comment w/o merge and rewrite commits on my own with this code)

**Comment by RisingOrange** [comment]
I dont have time right now so it will probably be faster if you use my code in your commit.

**Comment by RisingOrange** [comment]
I removed the aab dependency. (I just removed the addon.json file, didn't think about it earlier. You can compress the src/basic2cloze folder and it will work, possibly you have to add a manifest.json file if you want to install it locally from an .ankiaddon file.)

**Comment by RisingOrange** [comment]
If you don't want to upload it to AnkiWeb I can do it too ;)

**Comment by phu54321** [comment]
Sorry I was too lazy :(

Will look at it today

**Comment by phu54321** [comment]
Uh... sorry for late reply. I think you can upload your version side by side. There are too many changes and major code style changes. (Naming changed from camelCase to snake_case, things like `_findModelName` changed to `get_models`, like that). Thanks.

**Comment by RisingOrange** [comment]
No problem 👍

**Comment by RisingOrange** [comment]
To be sure: Are you planning to update the add-on in the future? I'm okay with doing that, in fact I thought about transferring the add-on to Anki Palace for who I work and keeping care of it. Is this ok with you?

**Pull request closed without merging**
